#!/bin/sh
# =============================================================================
# BSD 2-Clause License
#
# Copyright (c) 2019, Veaceslav Medvedev
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# =============================================================================

FCR='\033[1;31m' # Red
FCG='\033[1;32m' # Green
FCY='\033[0;33m' # Yellow
FCS='\033[0;37m' # Light gray (silver)
NC='\033[0m'

CMD="disallow-commits"
VERSION="1.0.0"
HOME="https://github.com/slavcodev/git-hooks-scripts"
ABOUT="${FCG}Branch protection${NC} version ${FCY}$VERSION${NC}"
HELP="$ABOUT

The 'pre-commit' hook to disallow commits into some branches.
Useful for example to disallow commits directly to master branch.

Multiple branches are supported.

${FCY}Example of config:${NC}
${FCS}~~~
[${CMD}]
  branch = master
  branch = development
~~~${NC}

$HOME

> Enjoy coding ❤️"

main() {
  branch_name="$(git rev-parse --abbrev-ref HEAD)"
  closed_branches=$(git config --get-all disallow-commits.branch)

  if [[ -z ${closed_branches} ]]; then
    closed_branches="master"
  fi

  for closed_branch in ${closed_branches} ; do
    if [[ "${branch_name}" =~ "${closed_branch}" ]]; then
      echo "${FCR}You can't commit directly to ${closed_branch} branch${NC}"
      exit 1
    fi
  done
}

case "$1" in
  -h|--help|-? )
    echo "${HELP}"
    ;;
  * )
    main
esac
